// frontend/src/App.jsx
/**
 * Raiz da Interface Web (container React do C4 Nivel 2).
 * Decide entre a tela de login e a aplicacao autenticada.
 */
import { useState } from 'react';
import { NavLink, Navigate, Route, Routes } from 'react-router-dom';
import LoginPage from './pages/LoginPage';
import RecepcaoPage from './pages/RecepcaoPage';
import FilaPage from './pages/FilaPage';
import { obterUsuario } from './services/api';
import { sair } from './services/washflowService';

export default function App() {
  const [usuario, setUsuario] = useState(obterUsuario);

  if (!usuario) {
    return <LoginPage aoEntrar={setUsuario} />;
  }

  function encerrar() {
    sair();
    setUsuario(null);
  }

  return (
    <>
      <header className="topo">
        <h1>WashFlow</h1>
        <NavLink to="/recepcao" className={({ isActive }) => (isActive ? 'ativo' : '')}>
          Recepcao
        </NavLink>
        <NavLink to="/fila" className={({ isActive }) => (isActive ? 'ativo' : '')}>
          Fila
        </NavLink>
        <span style={{ fontSize: '0.85rem' }}>
          {usuario.nome} ({usuario.perfil})
        </span>
        <button onClick={encerrar}>Sair</button>
      </header>

      <main className="conteudo">
        <Routes>
          <Route path="/recepcao" element={<RecepcaoPage />} />
          <Route path="/fila" element={<FilaPage />} />
          <Route path="*" element={<Navigate to="/fila" replace />} />
        </Routes>
      </main>
    </>
  );
}

// frontend/src/App.vue
<!--
  Raiz da Interface Web (container Vue.js do C4 Nivel 2).
  Exibe a barra de navegacao apenas quando ha sessao ativa.
-->
<script setup>
import { computed, ref, watch } from 'vue';
import { RouterLink, RouterView, useRoute, useRouter } from 'vue-router';
import { obterUsuario } from './services/api';
import { sair } from './services/washflowService';

const route = useRoute();
const router = useRouter();

const usuario = ref(obterUsuario());

// A sessao muda ao entrar e ao sair; reler a cada navegacao mantem a
// barra de navegacao coerente sem precisar de um store global.
watch(() => route.fullPath, () => {
  usuario.value = obterUsuario();
});

const mostrarBarra = computed(() => Boolean(usuario.value) && route.name !== 'login');

function encerrar() {
  sair();
  usuario.value = null;
  router.push({ name: 'login' });
}
</script>

<template>
  <header v-if="mostrarBarra" class="topo">
    <h1>WashFlow</h1>
    <RouterLink :to="{ name: 'recepcao' }" active-class="ativo">Recepcao</RouterLink>
    <RouterLink :to="{ name: 'fila' }" active-class="ativo">Fila</RouterLink>
    <span style="font-size: 0.85rem">
      {{ usuario.nome }} ({{ usuario.perfil }})
    </span>
    <button @click="encerrar">Sair</button>
  </header>

  <main :class="mostrarBarra ? 'conteudo' : ''">
    <RouterView />
  </main>
</template>
